### ISSUE TITLE
Handling of new mapnik2 expression syntax for names, ...

### ISSUE THREAD

**Issue by numenor** [mapnik/Cascadenik#12]
So far there seems to be no way to use the extended mapnik2 expression syntax for specifying the name for TextSymbolizers. Using the old syntax (specifying the name as second element of the selector) gives warnings:
    Deprecation Warning: symbolizer value now an expression, please wrap properly in brackets like "[name]"
But when using brackets, nothing changes (they just seem to be stripped away, as can be seen when using nested brackets); if using quotes, then no TextSymbolizer is written to the xml file at all. Without the possibility to specify brackets (and other operators in the expression; this currently leads to an error in cascadenic-compile.py, depending on what expression is tried), the additional capabilities of mapnik2 are not fully exploitable.

This concerns: branch mapnik2 (with latest commit on Nov 30th 2010)

**Comment by springmeyer** [comment]
thanks for the report - here is a temporary fix to work around the clashing syntax and will avoid the deprecation warning: https://github.com/mapnik/Cascadenik/commit/083cd73f04730a479fc9a1ec0bc90ba5333be261

I will keep this issue open because we need to give thought to how to support expressions in Cascadenik.
